version: '3.9'

name: se_school_test

services:
  db:
    image: postgres
    container_name: se_db
    restart: unless-stopped
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=${DB_DATABASE:-se_db}
      - POSTGRES_USER=${DB_USERNAME:-aksonov}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-xda5gzxda5gz}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  db-currency:
    image: postgres
    container_name: se_db_currency
    restart: unless-stopped
    ports:
      - "54330:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=${DB_DATABASE:-se_db_currency}
      - POSTGRES_USER=${DB_USERNAME:-aksonov}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-xda5gzxda5gz}
    volumes:
      - db_data_currency:/var/lib/postgresql/data
    networks:
      - backend_currency

  db-subscriber:
    image: postgres
    container_name: se_db_subscriber
    restart: unless-stopped
    ports:
      - "54331:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=${DB_DATABASE:-se_db_subscriber}
      - POSTGRES_USER=${DB_USERNAME:-aksonov}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-xda5gzxda5gz}
    volumes:
      - db_data_subscriber:/var/lib/postgresql/data
    networks:
      - backend_subscriber

  redis:
    image: redis:7-alpine3.19
    container_name: se_redis
    restart: always
    expose:
      - 63791
    ports:
      - "63791:6379"
    networks:
      - backend

  redis-currency:
    image: redis:7-alpine3.19
    container_name: se_redis_currency
    restart: always
    expose:
      - 63791
    ports:
      - "63800:6379"
    networks:
      - backend_currency

  redis-subscriber:
    image: redis:7-alpine3.19
    container_name: se_redis_subscriber
    restart: always
    expose:
      - 63791
    ports:
      - "63801:6379"
    networks:
      - backend_subscriber

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app
    image: se_app:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis
      - db
      - mail
    networks:
      - backend

  app-currency:
    build:
      context: ./services/currency
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_currency
    image: se_app_currency:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis-currency
      - db-currency
      - mail
    networks:
      - backend_currency

  app-subscriber:
    build:
      context: ./services/subscriber
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_subscriber
    image: se_app_subscriber:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis-subscriber
      - db-subscriber
      - mail
    networks:
      - backend_subscriber

  nginx:
    container_name: se_app_nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  nginx-currency:
    container_name: se_app_currency_nginx
    image: nginx:alpine
    ports:
      - "8001:80"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/currency.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-currency
    networks:
      - backend_currency

  nginx-subscriber:
    container_name: se_app_subscriber_nginx
    image: nginx:alpine
    ports:
      - "8002:80"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/subscriber.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-subscriber
    networks:
      - backend_subscriber

  queue:
    image: se_app:latest
    container_name: se_queue
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - redis
      - db
      - mail
    networks:
      - backend

  queue-currency:
    image: se_app_currency:latest
    container_name: se_queue_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - redis-currency
      - db-currency
      - mail
    networks:
      - backend_currency

  queue-subsciber:
    image: se_app_subscriber:latest
    container_name: se_queue_subscriber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - redis-subscriber
      - db-subscriber
      - mail
    networks:
      - backend_subscriber

  schedule:
    image: se_app:latest
    container_name: se_schedule
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - redis
      - db
      - mail
    networks:
      - backend

  schedule-currency:
    image: se_app_currency:latest
    container_name: se_schedule_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - redis-currency
      - db-currency
      - mail
    networks:
      - backend_currency

  schedule-subscriber:
    image: se_app_subscriber:latest
    container_name: se_schedule_subscriber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - redis-subscriber
      - db-subscriber
      - mail
    networks:
      - backend_subscriber

  mail:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend
      - backend_currency
      - backend_subscriber

volumes:
  db_data:
  db_data_currency:
  db_data_subscriber:

networks:
  backend:
    driver: bridge
  backend_currency:
    driver: bridge
  backend_subscriber:
    driver: bridge
