version: '3.9'

name: se_school_test

services:
  traefik:
    image: traefik:v2.8
    container_name: se_traefik
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend_currency
      - backend_subscriber

  db:
    image: postgres:alpine3.19
    container_name: se_db
    restart: unless-stopped
    ports:
      - "54330:5432"
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_MULTIPLE_DATABASES: "se_db_currency, se_db_subscriber, se_db_mailer"
      POSTGRES_USER: "aksonov"
      POSTGRES_PASSWORD: "xda5gzxda5gz"
    volumes:
      - se_db_data:/var/lib/postgresql/data
      - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - backend_currency
      - backend_subscriber
      - backend_mailer
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine3.19
    container_name: se_redis
    restart: always
    expose:
      - 63800
    ports:
      - "63800:6379"
    volumes:
      - se_redis_data:/data
    networks:
      - backend_currency
      - backend_subscriber
      - backend_mailer
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-mq

  app-currency:
    build:
      context: ./services/currency
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_currency
    image: se_app_currency:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - redis
      - db
    networks:
      - backend_currency
      - backend_subscriber

  app-subscriber:
    build:
      context: ./services/subscriber
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_subscriber
    image: se_app_subscriber:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - redis
      - db
    networks:
      - backend_subscriber
      - backend_currency
      - rabbit-mq

  app-mailer:
    build:
      context: ./services/mailer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_mailer
    image: se_app_mailer:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/mailer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/mailer.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - redis
      - db
      - mail
    networks:
      - backend_mailer
      - rabbit-mq

  nginx-currency:
    container_name: se_app_currency_nginx
    image: nginx:alpine
    ports:
      - "8001:80"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/currency.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-currency.rule=PathPrefix(`/api/rate`)"
      - "traefik.http.routers.nginx-currency.entrypoints=web"
      - "traefik.http.services.nginx-currency.loadbalancer.server.port=80"
    depends_on:
      - app-currency
    networks:
      - backend_currency

  nginx-subscriber:
    container_name: se_app_subscriber_nginx
    image: nginx:alpine
    ports:
      - "8002:80"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/subscriber.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-subscriber.rule=PathPrefix(`/api/subscribe`)"
      - "traefik.http.routers.nginx-subscriber.entrypoints=web"
      - "traefik.http.services.nginx-subscriber.loadbalancer.server.port=80"
    depends_on:
      - app-subscriber
    networks:
      - backend_subscriber

  queue-currency:
    image: se_app_currency:latest
    container_name: se_queue_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-currency
    networks:
      - backend_currency

  queue-mailer:
    image: se_app_mailer:latest
    container_name: se_queue_mailer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/mailer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/mailer.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-mailer
    networks:
      - backend_mailer

  schedule-currency:
    image: se_app_currency:latest
    container_name: se_schedule_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - app-currency
    networks:
      - backend_currency

  schedule-subscriber:
    image: se_app_subscriber:latest
    container_name: se_schedule_subscriber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - app-subscriber
    networks:
      - backend_subscriber

  mail:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend_mailer

volumes:
  se_db_data:
  se_redis_data:

networks:
  backend_currency:
    driver: bridge
  backend_subscriber:
    driver: bridge
  backend_mailer:
    driver: bridge
  rabbit-mq:
    driver: bridge
