version: '3.9'

name: se_school_test

services:
  traefik:
    image: traefik:v2.8
    container_name: se_traefik
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: postgres:alpine3.19
    container_name: se_db
    restart: unless-stopped
    ports:
      - "54330:5432"
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_MULTIPLE_DATABASES: "se_db_currency, se_db_subscriber, se_db_mailer, se_db_customer, se_db_shared"
      POSTGRES_USER: "aksonov"
      POSTGRES_PASSWORD: "xda5gzxda5gz"
    volumes:
      - se_db_data:/var/lib/postgresql/data
      - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  app-currency:
    build:
      context: ./services/currency
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_currency
    image: se_app_currency:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - db

  app-subscriber:
    build:
      context: ./services/subscriber
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_subscriber
    image: se_app_subscriber:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - db

  app-mailer:
    build:
      context: ./services/mailer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_mailer
    image: se_app_mailer:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/mailer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/mailer.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - db
      - mail

  app-customer:
    build:
      context: ./services/customer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: se_app_customer
    image: se_app_customer:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/customer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/customer.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbitmq
      - db

  nginx-currency:
    container_name: se_app_currency_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/currency.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"

      # Route for /api/rate
      - "traefik.http.routers.nginx-currency-rate.rule=PathPrefix(`/api/rate`)"
      - "traefik.http.routers.nginx-currency-rate.entrypoints=web"
      - "traefik.http.services.nginx-currency.loadbalancer.server.port=80"
    depends_on:
      - app-currency

  nginx-subscriber:
    container_name: se_app_subscriber_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/nginx/subscriber.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"

      # Route for /api/subscribe
      - "traefik.http.routers.nginx-subscriber-subscribe.rule=PathPrefix(`/api/subscribe`)"
      - "traefik.http.routers.nginx-subscriber-subscribe.entrypoints=web"
      - "traefik.http.services.nginx-subscriber.loadbalancer.server.port=80"

      # Route for /api/unsubscribe
      - "traefik.http.routers.nginx-subscriber-unsubscribe.rule=PathPrefix(`/api/unsubscribe`)"
      - "traefik.http.routers.nginx-subscriber-unsubscribe.entrypoints=web"
      - "traefik.http.services.nginx-subscriber.loadbalancer.server.port=80"
    depends_on:
      - app-subscriber

  nginx-mailer:
    container_name: se_app_mailer_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./services/mailer:/app
      - ./docker/nginx/mailer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-mailer

  nginx-customer:
    container_name: se_app_customer_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./services/customer:/app
      - ./docker/nginx/customer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-customer

  queue-currency:
    image: se_app_currency:latest
    container_name: se_queue_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-currency

  queue-subscriber:
    image: se_app_subscriber:latest
    container_name: se_queue_subscriber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-subscriber

  queue-mailer:
    image: se_app_mailer:latest
    container_name: se_queue_mailer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/mailer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/mailer.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-mailer

  queue-customer:
    image: se_app_customer:latest
    container_name: se_queue_customer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./services/customer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/customer.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan queue:work
    depends_on:
      - app-subscriber

  schedule-currency:
    image: se_app_currency:latest
    container_name: se_schedule_currency
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/currency:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/currency.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - app-currency

  schedule-subscriber:
    image: se_app_subscriber:latest
    container_name: se_schedule_subscriber
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/subscriber:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/subscriber.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - app-subscriber

  schedule-mailer:
    image: se_app_mailer:latest
    container_name: se_schedule_mailer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    volumes:
      - ./services/mailer:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/mailer.conf:/usr/local/etc/php-fpm.d/www.conf
    command: php artisan schedule:work
    depends_on:
      - app-mailer

  mail:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.localhost`)"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"

  prometheus:
    image: prom/prometheus
    container_name: se_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app-currency
      - app-subscriber
      - app-mailer
      - app-customer

  grafana:
    image: grafana/grafana
    container_name: se_grafana
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    depends_on:
      - prometheus

volumes:
  se_db_data:
