{
 "title": "Dashboard-1",
 "time": { "from": "2024-07-21T23:35:21.495Z", "to": "2024-07-22T00:05:21.495Z" },
 "panels": [
  {
   "title": "Currency rates count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_currency_rates", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "subscriber_subscribers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Customer count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "customer_customers", "legendFormat": "__auto" }
   ]
  }
 ]
}